export const GUIDE_ENGLISH_TRANSLATION_OVERRIDES: Readonly<
  Record<string, string>
> = {
  temas: 'topics',
  tema: 'topic',
  'Angular moderno': 'Modern Angular',
  'Criterio Senior': 'Senior judgment',
  'TypeScript avanzado': 'Advanced TypeScript',
  'Ir al contenido': 'Skip to content',
  'Adrian Cabello, Full-Stack Product Engineer y Tech Lead':
    'Adrian Cabello, Full-Stack Product Engineer and Tech Lead',
  'HTML, CSS, JavaScript, TypeScript, Angular moderno, RxJS, browser, arquitectura, performance, testing, seguridad, system design y liderazgo técnico.':
    'HTML, CSS, JavaScript, TypeScript, modern Angular, RxJS, browser internals, architecture, performance, testing, security, system design and technical leadership.',
  'Fundamentos web': 'Web fundamentals',
  'HTML, CSS, JavaScript y TypeScript, desde la base hasta preguntas avanzadas.':
    'HTML, CSS, JavaScript and TypeScript, from first principles to advanced interview questions.',
  'Plataforma y arquitectura': 'Platform and architecture',
  'Browser, DOM, red, límites, patrones, SOLID y evolución del código.':
    'Browser internals, DOM, networking, boundaries, patterns, SOLID and code evolution.',
  'Cómo razonar y responder como Senior':
    'How to reason and answer as a Senior engineer',
  'Banco rápido': 'Quick-fire questions',
  'Abrir tema': 'Open topic',
  'Cerrar tema': 'Collapse topic',
  '¿Temporal Dead Zone?': 'Temporal Dead Zone?',
  '`var` usa scope de función y permite redeclaración. `let` y `const` usan scope de bloque y temporal dead zone. `const` impide reasignar la variable, pero el valor referenciado puede mutar.':
    '`var` has function scope and allows redeclaration. `let` and `const` have block scope and remain in the Temporal Dead Zone until initialized. `const` prevents reassignment of the binding, but the referenced value can still mutate.',
  '`header`, `nav`, `main`, `article`, `section`, `aside` y `footer` describen la función de cada región. Navegadores y tecnologías asistivas usan esa estructura para crear landmarks. `div` y `span` agrupan contenido sin añadir significado.':
    '`header`, `nav`, `main`, `article`, `section`, `aside` and `footer` describe the purpose of each region. Browsers and assistive technologies use that structure to expose landmarks. `div` and `span` group content without adding meaning.',
  '`a` navega y necesita `href`; `button` ejecuta una acción. `target=_blank` requiere una política de `rel` apropiada para reducir acceso a opener.':
    '`a` navigates and requires an `href`; `button` performs an action. `target=_blank` requires an appropriate `rel` policy to restrict opener access.',
  'Una tabla de datos se compone con `caption`, `thead`, `tbody`, celdas `th` y relaciones `scope`. Esa estructura permite asociar cada dato con sus encabezados. Las tablas usadas para layout comunican relaciones inexistentes y dificultan el responsive design.':
    'A data table uses `caption`, `thead`, `tbody`, `th` cells and `scope` relationships. This structure associates every data cell with its headers. Tables used for layout communicate relationships that do not exist and make responsive design harder.',
  'CSS resuelve una cascada antes de calcular layout y paint. Las preguntas clásicas empiezan con selectores; las Senior llegan a stacking contexts, containment y estabilidad visual.':
    'CSS resolves the cascade before computing layout and paint. Classic questions begin with selectors; Senior-level questions reach stacking contexts, containment and visual stability.',
  'Aceptaría `value == null` si el estándar del equipo permite comprobar `null` y `undefined` juntos. Para el resto prefiero `===` porque evita que quien lee tenga que reconstruir la tabla de coerción.':
    'I would accept `value == null` if the team standard allows checking `null` and `undefined` together. Otherwise I prefer `===`, because readers do not need to reconstruct the coercion table.',
  'Separá mecanismo de decisión. «OnPush reduce comprobaciones» describe un efecto. «Uso OnPush con estado inmutable porque los cambios llegan por inputs y signals» explica una decisión. La segunda respuesta permite evaluar si entendés cuándo la herramienta encaja.':
    'Separate mechanism from decision. “OnPush reduces checks” describes an effect. “I use OnPush with immutable state because changes arrive through inputs and signals” explains a decision. The second answer shows whether you understand when the tool fits.',
  'Nombrá las restricciones que cambian la solución: volumen de datos, frecuencia de actualización, SEO, latencia, accesibilidad, seguridad, soporte de navegadores y capacidad del equipo. Si la pregunta no las informa, declaralas como supuestos en vez de inventar un escenario silenciosamente.':
    'Name the constraints that change the solution: data volume, update frequency, SEO, latency, accessibility, security, browser support and team capacity. If the question omits them, state your assumptions instead of silently inventing a scenario.',
  'Explicá cómo validarías la decisión. Rendimiento se comprueba con métricas como LCP, INP, tamaño de bundle o tiempo de tarea; una migración se valida con tests, telemetría, despliegue gradual y rollback; una mejora de equipo se valida con lead time, defectos o carga operativa.':
    'Explain how you would validate the decision. Performance is checked with metrics such as LCP, INP, bundle size or task duration; a migration with tests, telemetry, gradual rollout and rollback; a team improvement with lead time, defects or operational load.',
  'Una respuesta débil enumera herramientas: «usaría Signals, OnPush y lazy loading». Una respuesta sólida conecta problema y evidencia: «el perfil mostró demasiadas vistas comprobadas; moví el estado local a Signals, mantuve referencias inmutables y medí menos scripting sin cambiar el comportamiento».':
    'A weak answer lists tools: “I would use Signals, OnPush and lazy loading.” A strong answer connects the problem to evidence: “Profiling showed too many checked views; I moved local state to Signals, kept immutable references and measured less scripting time without changing behavior.”',
  'Si no recordás una API exacta, no inventes. Explicá el modelo que sí conocés, aislá el detalle dudoso y decí cómo lo verificarías en la documentación o con una prueba mínima. El razonamiento correcto es más valioso que una firma memorizada incorrectamente.':
    'If you do not remember an exact API, do not invent it. Explain the model you do know, isolate the uncertain detail and say how you would verify it in the documentation or with a minimal test. Correct reasoning is more valuable than an incorrectly memorized signature.',
  "Una shallow copy crea un objeto o array nuevo, pero copia por referencia los valores anidados. Por ejemplo, con `const original = { user: { name: 'Ana' } }; const copy = { ...original };`, se cumple `copy !== original`, pero `copy.user === original.user`; por eso `copy.user.name = 'Luis'` también modifica `original.user.name`. Spread, `Object.assign`, `Array.from` y `slice` hacen copias superficiales. Una deep copy duplica recursivamente la estructura para que los objetos anidados no compartan identidad. `structuredClone(original)` sirve para muchos datos nativos y ciclos, pero no clona funciones, elementos DOM ni conserva el comportamiento de todas las instancias de clases. No hago una copia profunda por defecto: cuesta CPU y memoria, y puede romper identidades que la aplicación necesita. Para actualizar estado prefiero copiar sólo el camino modificado, por ejemplo `{ ...state, user: { ...state.user, name: 'Luis' } }`; así mantengo inmutabilidad y structural sharing sin duplicar todo el grafo.":
    "A shallow copy creates a new object or array, but nested values are copied by reference. For example, with `const original = { user: { name: 'Ana' } }; const copy = { ...original };`, `copy !== original`, but `copy.user === original.user`; therefore, `copy.user.name = 'Luis'` also changes `original.user.name`. Spread, `Object.assign`, `Array.from`, and `slice` make shallow copies. A deep copy recursively duplicates the structure so nested objects do not share identity. `structuredClone(original)` works for many native data types and cycles, but it does not clone functions or DOM elements, and it does not preserve the behavior of every class instance. I do not deep-clone by default: it costs CPU and memory and can break identities the application relies on. For state updates, I prefer copying only the changed path, such as `{ ...state, user: { ...state.user, name: 'Luis' } }`; this preserves immutability and structural sharing without duplicating the entire object graph.",
  'Al entrar en un bloque, JavaScript crea los bindings de `let`, `const` y `class`, pero los deja sin inicializar hasta ejecutar su declaración. Ese intervalo es la Temporal Dead Zone. Leer el binding durante ese tramo lanza `ReferenceError`: `console.log(total); let total = 1;`. Incluso `typeof total` falla si `total` está en la TDZ, a diferencia de una variable que no existe. Con `var`, en cambio, el binding se inicializa con `undefined`, por lo que el acceso prematuro no falla y puede ocultar un error de orden. La TDZ existe para que una variable con scope de bloque no se use antes de tener el valor que su declaración promete. No significa que `let` y `const` no tengan hoisting: sus bindings se crean al entrar al scope, pero todavía no son accesibles.':
    'When JavaScript enters a block, it creates the bindings for `let`, `const`, and `class`, but leaves them uninitialized until their declaration executes. That interval is the Temporal Dead Zone. Reading the binding during it throws a `ReferenceError`: `console.log(total); let total = 1;`. Even `typeof total` fails when `total` is in the TDZ, unlike a variable that does not exist. With `var`, the binding is initialized to `undefined`, so early access does not fail and can hide an ordering bug. The TDZ prevents a block-scoped variable from being used before it has the value promised by its declaration. It does not mean `let` and `const` are not hoisted: their bindings are created when entering the scope, but they are not accessible yet.',
  "Sí, pero sólo usaría deliberadamente `value == null` cuando quiero aceptar exactamente `null` o `undefined`. La comparación es verdadera para esos dos valores y falsa para `0`, `false`, `''` y `NaN`; por ejemplo, `if (response.middleName == null)` detecta que el campo opcional no llegó sin rechazar una cadena vacía válida. Es una excepción conocida de Abstract Equality y conviene permitirla explícitamente con una regla como `eqeqeq: ['error', 'always', { null: 'ignore' }]`. En el resto del código uso `===` y `!==`, porque `==` aplica coerciones difíciles de leer: `'' == 0`, `'0' == false` y `[] == false` son verdaderas. Si el equipo prioriza máxima explicitud, escribo `value === null || value === undefined`; comunica el mismo contrato sin depender de conocer la excepción.":
    "Yes, but I would deliberately use `value == null` only when I want to accept exactly `null` or `undefined`. The comparison is true for those two values and false for `0`, `false`, `''`, and `NaN`; for example, `if (response.middleName == null)` detects that an optional field is missing without rejecting a valid empty string. This is a well-known Abstract Equality exception and should be allowed explicitly with a rule such as `eqeqeq: ['error', 'always', { null: 'ignore' }]`. Everywhere else I use `===` and `!==`, because `==` applies coercions that are difficult to read: `'' == 0`, `'0' == false`, and `[] == false` are all true. If the team prioritizes maximum explicitness, I write `value === null || value === undefined`; it communicates the same contract without relying on knowledge of the exception.",
};
