export const GUIDE_ENGLISH_TRANSLATION_OVERRIDES: Readonly<
  Record<string, string>
> = {
  temas: 'topics',
  tema: 'topic',
  'Angular moderno': 'Modern Angular',
  'Criterio Senior': 'Senior judgment',
  'TypeScript avanzado': 'Advanced TypeScript',
  'Ir al contenido': 'Skip to content',
  'Adrian Cabello, Full-Stack Product Engineer y Tech Lead':
    'Adrian Cabello, Full-Stack Product Engineer and Tech Lead',
  'HTML, CSS, JavaScript, TypeScript, Angular moderno, RxJS, browser, arquitectura, performance, testing, seguridad, system design y liderazgo técnico.':
    'HTML, CSS, JavaScript, TypeScript, modern Angular, RxJS, browser internals, architecture, performance, testing, security, system design and technical leadership.',
  'Fundamentos web': 'Web fundamentals',
  'HTML, CSS, JavaScript y TypeScript, desde la base hasta preguntas avanzadas.':
    'HTML, CSS, JavaScript and TypeScript, from first principles to advanced interview questions.',
  'Plataforma y arquitectura': 'Platform and architecture',
  'Browser, DOM, red, límites, patrones, SOLID y evolución del código.':
    'Browser internals, DOM, networking, boundaries, patterns, SOLID and code evolution.',
  'Cómo razonar y responder como Senior':
    'How to reason and answer as a Senior engineer',
  'Banco rápido': 'Quick-fire questions',
  'Abrir tema': 'Open topic',
  'Cerrar tema': 'Collapse topic',
  '¿Temporal Dead Zone?': 'Temporal Dead Zone?',
  '`var` usa scope de función y permite redeclaración. `let` y `const` usan scope de bloque y temporal dead zone. `const` impide reasignar la variable, pero el valor referenciado puede mutar.':
    '`var` has function scope and allows redeclaration. `let` and `const` have block scope and remain in the Temporal Dead Zone until initialized. `const` prevents reassignment of the binding, but the referenced value can still mutate.',
  '`header`, `nav`, `main`, `article`, `section`, `aside` y `footer` describen la función de cada región. Navegadores y tecnologías asistivas usan esa estructura para crear landmarks. `div` y `span` agrupan contenido sin añadir significado.':
    '`header`, `nav`, `main`, `article`, `section`, `aside` and `footer` describe the purpose of each region. Browsers and assistive technologies use that structure to expose landmarks. `div` and `span` group content without adding meaning.',
  '`a` navega y necesita `href`; `button` ejecuta una acción. `target=_blank` requiere una política de `rel` apropiada para reducir acceso a opener.':
    '`a` navigates and requires an `href`; `button` performs an action. `target=_blank` requires an appropriate `rel` policy to restrict opener access.',
  'Una tabla de datos se compone con `caption`, `thead`, `tbody`, celdas `th` y relaciones `scope`. Esa estructura permite asociar cada dato con sus encabezados. Las tablas usadas para layout comunican relaciones inexistentes y dificultan el responsive design.':
    'A data table uses `caption`, `thead`, `tbody`, `th` cells and `scope` relationships. This structure associates every data cell with its headers. Tables used for layout communicate relationships that do not exist and make responsive design harder.',
  'CSS resuelve una cascada antes de calcular layout y paint. Las preguntas clásicas empiezan con selectores; las Senior llegan a stacking contexts, containment y estabilidad visual.':
    'CSS resolves the cascade before computing layout and paint. Classic questions begin with selectors; Senior-level questions reach stacking contexts, containment and visual stability.',
  'Aceptaría `value == null` si el estándar del equipo permite comprobar `null` y `undefined` juntos. Para el resto prefiero `===` porque evita que quien lee tenga que reconstruir la tabla de coerción.':
    'I would accept `value == null` if the team standard allows checking `null` and `undefined` together. Otherwise I prefer `===`, because readers do not need to reconstruct the coercion table.',
  'Separá mecanismo de decisión. «OnPush reduce comprobaciones» describe un efecto. «Uso OnPush con estado inmutable porque los cambios llegan por inputs y signals» explica una decisión. La segunda respuesta permite evaluar si entendés cuándo la herramienta encaja.':
    'Separate mechanism from decision. “OnPush reduces checks” describes an effect. “I use OnPush with immutable state because changes arrive through inputs and signals” explains a decision. The second answer shows whether you understand when the tool fits.',
  'Nombrá las restricciones que cambian la solución: volumen de datos, frecuencia de actualización, SEO, latencia, accesibilidad, seguridad, soporte de navegadores y capacidad del equipo. Si la pregunta no las informa, declaralas como supuestos en vez de inventar un escenario silenciosamente.':
    'Name the constraints that change the solution: data volume, update frequency, SEO, latency, accessibility, security, browser support and team capacity. If the question omits them, state your assumptions instead of silently inventing a scenario.',
  'Explicá cómo validarías la decisión. Rendimiento se comprueba con métricas como LCP, INP, tamaño de bundle o tiempo de tarea; una migración se valida con tests, telemetría, despliegue gradual y rollback; una mejora de equipo se valida con lead time, defectos o carga operativa.':
    'Explain how you would validate the decision. Performance is checked with metrics such as LCP, INP, bundle size or task duration; a migration with tests, telemetry, gradual rollout and rollback; a team improvement with lead time, defects or operational load.',
  'Una respuesta débil enumera herramientas: «usaría Signals, OnPush y lazy loading». Una respuesta sólida conecta problema y evidencia: «el perfil mostró demasiadas vistas comprobadas; moví el estado local a Signals, mantuve referencias inmutables y medí menos scripting sin cambiar el comportamiento».':
    'A weak answer lists tools: “I would use Signals, OnPush and lazy loading.” A strong answer connects the problem to evidence: “Profiling showed too many checked views; I moved local state to Signals, kept immutable references and measured less scripting time without changing behavior.”',
  'Si no recordás una API exacta, no inventes. Explicá el modelo que sí conocés, aislá el detalle dudoso y decí cómo lo verificarías en la documentación o con una prueba mínima. El razonamiento correcto es más valioso que una firma memorizada incorrectamente.':
    'If you do not remember an exact API, do not invent it. Explain the model you do know, isolate the uncertain detail and say how you would verify it in the documentation or with a minimal test. Correct reasoning is more valuable than an incorrectly memorized signature.',
  "Una shallow copy crea un objeto o array nuevo, pero copia por referencia los valores anidados. Por ejemplo, con `const original = { user: { name: 'Ana' } }; const copy = { ...original };`, se cumple `copy !== original`, pero `copy.user === original.user`; por eso `copy.user.name = 'Luis'` también modifica `original.user.name`. Spread, `Object.assign`, `Array.from` y `slice` hacen copias superficiales. Una deep copy duplica recursivamente la estructura para que los objetos anidados no compartan identidad. `structuredClone(original)` sirve para muchos datos nativos y ciclos, pero no clona funciones, elementos DOM ni conserva el comportamiento de todas las instancias de clases. No hago una copia profunda por defecto: cuesta CPU y memoria, y puede romper identidades que la aplicación necesita. Para actualizar estado prefiero copiar sólo el camino modificado, por ejemplo `{ ...state, user: { ...state.user, name: 'Luis' } }`; así mantengo inmutabilidad y structural sharing sin duplicar todo el grafo.":
    "A shallow copy creates a new object or array, but nested values are copied by reference. For example, with `const original = { user: { name: 'Ana' } }; const copy = { ...original };`, `copy !== original`, but `copy.user === original.user`; therefore, `copy.user.name = 'Luis'` also changes `original.user.name`. Spread, `Object.assign`, `Array.from`, and `slice` make shallow copies. A deep copy recursively duplicates the structure so nested objects do not share identity. `structuredClone(original)` works for many native data types and cycles, but it does not clone functions or DOM elements, and it does not preserve the behavior of every class instance. I do not deep-clone by default: it costs CPU and memory and can break identities the application relies on. For state updates, I prefer copying only the changed path, such as `{ ...state, user: { ...state.user, name: 'Luis' } }`; this preserves immutability and structural sharing without duplicating the entire object graph.",
  'Al entrar en un bloque, JavaScript crea los bindings de `let`, `const` y `class`, pero los deja sin inicializar hasta ejecutar su declaración. Ese intervalo es la Temporal Dead Zone. Leer el binding durante ese tramo lanza `ReferenceError`: `console.log(total); let total = 1;`. Incluso `typeof total` falla si `total` está en la TDZ, a diferencia de una variable que no existe. Con `var`, en cambio, el binding se inicializa con `undefined`, por lo que el acceso prematuro no falla y puede ocultar un error de orden. La TDZ existe para que una variable con scope de bloque no se use antes de tener el valor que su declaración promete. No significa que `let` y `const` no tengan hoisting: sus bindings se crean al entrar al scope, pero todavía no son accesibles.':
    'When JavaScript enters a block, it creates the bindings for `let`, `const`, and `class`, but leaves them uninitialized until their declaration executes. That interval is the Temporal Dead Zone. Reading the binding during it throws a `ReferenceError`: `console.log(total); let total = 1;`. Even `typeof total` fails when `total` is in the TDZ, unlike a variable that does not exist. With `var`, the binding is initialized to `undefined`, so early access does not fail and can hide an ordering bug. The TDZ prevents a block-scoped variable from being used before it has the value promised by its declaration. It does not mean `let` and `const` are not hoisted: their bindings are created when entering the scope, but they are not accessible yet.',
  "Sí, pero sólo usaría deliberadamente `value == null` cuando quiero aceptar exactamente `null` o `undefined`. La comparación es verdadera para esos dos valores y falsa para `0`, `false`, `''` y `NaN`; por ejemplo, `if (response.middleName == null)` detecta que el campo opcional no llegó sin rechazar una cadena vacía válida. Es una excepción conocida de Abstract Equality y conviene permitirla explícitamente con una regla como `eqeqeq: ['error', 'always', { null: 'ignore' }]`. En el resto del código uso `===` y `!==`, porque `==` aplica coerciones difíciles de leer: `'' == 0`, `'0' == false` y `[] == false` son verdaderas. Si el equipo prioriza máxima explicitud, escribo `value === null || value === undefined`; comunica el mismo contrato sin depender de conocer la excepción.":
    "Yes, but I would deliberately use `value == null` only when I want to accept exactly `null` or `undefined`. The comparison is true for those two values and false for `0`, `false`, `''`, and `NaN`; for example, `if (response.middleName == null)` detects that an optional field is missing without rejecting a valid empty string. This is a well-known Abstract Equality exception and should be allowed explicitly with a rule such as `eqeqeq: ['error', 'always', { null: 'ignore' }]`. Everywhere else I use `===` and `!==`, because `==` applies coercions that are difficult to read: `'' == 0`, `'0' == false`, and `[] == false` are all true. If the team prioritizes maximum explicitness, I write `value === null || value === undefined`; it communicates the same contract without relying on knowledge of the exception.",
  'La coerción es la conversión de un valor de un tipo a otro. Es explícita cuando el código llama a `Number(value)`, `String(value)` o `Boolean(value)`, e implícita cuando el lenguaje convierte porque un operador o contexto necesita otro tipo. Formularios, query params, atributos DOM y storage entregan strings aunque representen números o booleanos; convertir y validar en esa frontera evita que la coerción se propague al dominio.':
    'Coercion is the conversion of a value from one type to another. It is explicit when code calls `Number(value)`, `String(value)`, or `Boolean(value)`, and implicit when the language converts because an operator or context requires another type. Forms, query parameters, DOM attributes, and storage return strings even when they represent numbers or booleans; converting and validating at that boundary prevents coercion from spreading into the domain.',
  "Cuando un operador necesita convertir un objeto a primitivo, JavaScript ejecuta la operación abstracta `ToPrimitive`. Primero respeta `Symbol.toPrimitive` y, según el hint, consulta `valueOf` y `toString` hasta obtener un primitivo. Por eso `[]` se convierte en `''`, `[1, 2]` en `'1,2'` y un objeto común suele producir `'[object Object]'`; después el operador continúa con la conversión numérica o textual que corresponda.":
    "When an operator needs to convert an object to a primitive, JavaScript runs the abstract `ToPrimitive` operation. It first honors `Symbol.toPrimitive` and, depending on the hint, checks `valueOf` and `toString` until it obtains a primitive. That is why `[]` becomes `''`, `[1, 2]` becomes `'1,2'`, and a plain object usually produces `'[object Object]'`; the operator then continues with the required numeric or string conversion.",
  "El operador `+` es especial: después de convertir objetos a primitivos, concatena si alguno de los operandos es string; si no, realiza suma numérica. `1 + '2'` produce `'12'`, mientras `'5' - 2`, `'5' * 2` y `'5' / 2` convierten a número. Los template literals fuerzan string y los contextos de `if`, `!`, `&&` y `||` usan conversión booleana.":
    "The `+` operator is special: after converting objects to primitives, it concatenates if either operand is a string; otherwise it performs numeric addition. `1 + '2'` produces `'12'`, while `'5' - 2`, `'5' * 2`, and `'5' / 2` convert to number. Template literals force string conversion, while `if`, `!`, `&&`, and `||` use boolean conversion.",
  "Las conversiones tienen bordes que conviene conocer: `Number('')` y `Number(null)` producen `0`, `Number(undefined)` produce `NaN`, y `Boolean('false')` es `true` porque cualquier string no vacío es truthy. `Number` exige que toda la cadena represente un número; `parseInt('10px', 10)` acepta el prefijo numérico. Ninguna de las dos reemplaza validar rango, formato y finitud con `Number.isFinite`.":
    "Conversions have important edge cases: `Number('')` and `Number(null)` produce `0`, `Number(undefined)` produces `NaN`, and `Boolean('false')` is `true` because every non-empty string is truthy. `Number` requires the entire string to represent a number; `parseInt('10px', 10)` accepts a numeric prefix. Neither replaces validating range, format, and finiteness with `Number.isFinite`.",
  'Un closure es la combinación de una función con el entorno léxico donde fue creada. La función puede ejecutarse después de que terminó la llamada exterior y seguir resolviendo parámetros y variables de ese entorno. `makeCounter` puede declarar `let count = 0` y devolver una función que incrementa `count`; cada llamada a `makeCounter()` crea un binding privado e independiente.':
    'A closure is the combination of a function and the lexical environment where it was created. The function can run after the outer call has finished and still resolve parameters and variables from that environment. `makeCounter` can declare `let count = 0` and return a function that increments `count`; every call to `makeCounter()` creates a private, independent binding.',
  'El closure conserva bindings, no una fotografía de sus valores. Si el binding cambia, las funciones que lo cerraron observan el valor actual. Esto permite estado privado y callbacks coordinados, pero también explica bugs cuando varias funciones comparten accidentalmente una misma variable mutable.':
    'A closure preserves bindings, not a snapshot of their values. If a binding changes, the functions that close over it observe the current value. This enables private state and coordinated callbacks, but also explains bugs when several functions accidentally share the same mutable variable.',
  'En un loop, `var` crea un único binding con scope de función, por lo que callbacks diferidos suelen leer el valor final. `let` crea un binding nuevo por iteración. Antes de `let`, una IIFE o una factory recibía el valor de cada vuelta y creaba un entorno distinto.':
    'In a loop, `var` creates one function-scoped binding, so deferred callbacks usually read the final value. `let` creates a new binding for each iteration. Before `let`, an IIFE or factory received each iteration value and created a separate environment.',
  'Closures sostienen factories, currying, memoization, event handlers y callbacks asíncronos. El entorno permanece vivo mientras una función alcanzable lo necesite: no es una fuga por sí mismo, pero puede retener DOM, caches o respuestas grandes. El cleanup debe remover listeners, cancelar timers o suscripciones y evitar capturar objetos completos cuando alcanza con un identificador o un dato pequeño.':
    'Closures support factories, currying, memoization, event handlers, and asynchronous callbacks. The environment remains alive while a reachable function needs it: that is not a leak by itself, but it can retain DOM nodes, caches, or large responses. Cleanup should remove listeners, cancel timers or subscriptions, and avoid capturing entire objects when an identifier or small value is enough.',
  '¿Qué es un closure y cuándo se crea?':
    'What is a closure, and when is it created?',
  'Un closure es una función junto con las referencias a los bindings de su entorno léxico. Se determina cuando la función se crea, no cuando se invoca. Por ejemplo, `function makeCounter() { let count = 0; return () => ++count; }` devuelve una función que sigue accediendo a `count` después de que `makeCounter` terminó. `const a = makeCounter(); const b = makeCounter();` crea dos entornos: `a()` devuelve `1`, luego `2`, mientras `b()` comienza en `1`. El runtime conserva sólo los entornos que todavía son alcanzables; por eso un closure permite estado privado sin convertir `count` en una variable global.':
    'A closure is a function together with references to the bindings in its lexical environment. It is determined when the function is created, not when it is invoked. For example, `function makeCounter() { let count = 0; return () => ++count; }` returns a function that keeps accessing `count` after `makeCounter` finishes. `const a = makeCounter(); const b = makeCounter();` creates two environments: `a()` returns `1`, then `2`, while `b()` starts at `1`. The runtime preserves only environments that remain reachable, so a closure provides private state without turning `count` into a global variable.',
  '¿Un closure captura el valor o el binding?':
    'Does a closure capture the value or the binding?',
  'Captura el binding, es decir, la celda donde vive el valor, no una fotografía inmutable. Con `let rate = 1; const price = value => value * rate; rate = 2;`, `price(10)` devuelve `20` porque lee el valor actual de `rate`. Varias funciones pueden compartir el mismo binding y observar sus cambios. Si necesito congelar el valor de un momento, creo otro binding pasando el dato a una factory: `const withRate = rate => value => value * rate`. Cada llamada recibe su propio parámetro `rate`.':
    'It captures the binding—the cell where the value lives—not an immutable snapshot. With `let rate = 1; const price = value => value * rate; rate = 2;`, `price(10)` returns `20` because it reads the current value of `rate`. Several functions can share the same binding and observe its changes. If I need to freeze a value at a point in time, I create another binding by passing the value to a factory: `const withRate = rate => value => value * rate`. Each call receives its own `rate` parameter.',
  '¿Por qué un loop con `var` y callbacks suele imprimir el valor final?':
    'Why does a loop with `var` and callbacks usually print the final value?',
  '¿Cómo puede un closure retener memoria innecesariamente?':
    'How can a closure retain unnecessary memory?',
  '¿Qué diferencia hay entre coerción implícita y conversión explícita?':
    'What is the difference between implicit coercion and explicit conversion?',
  '¿Qué es `ToPrimitive` y por qué importa?':
    'What is `ToPrimitive`, and why does it matter?',
  '¿Coerción?': 'Coercion?',
  'Conversión entre tipos. Puede ser explícita con `Number`, `String` o `Boolean`, o implícita cuando un operador o contexto necesita otro tipo.':
    'Conversion between types. It can be explicit with `Number`, `String`, or `Boolean`, or implicit when an operator or context requires another type.',
  'Una función conserva los bindings del entorno léxico donde fue creada, incluso si se ejecuta después de que terminó la función exterior. Conserva bindings vivos, no una copia congelada de sus valores.':
    'A function preserves the bindings from the lexical environment where it was created, even when it runs after the outer function has finished. It preserves live bindings, not a frozen copy of their values.',
  'Función junto con su entorno léxico: puede seguir leyendo o modificando los bindings capturados cuando se ejecuta fuera de la llamada que los creó.':
    'A function together with its lexical environment: it can keep reading or modifying captured bindings when it runs outside the call that created them.',
  "La igualdad abstracta no compara directamente array y boolean. Primero convierte `false` a número: `0`. Después aplica `ToPrimitive` al array: `[].toString()` produce `''`. Como ahora compara string con number, convierte `''` a `0`; el resultado final es `0 == 0`, que es `true`. En cambio, `[] === false` es `false` porque los tipos son distintos y no existe coerción. No memorizaría solamente este resultado: seguir los pasos boolean → number, object → primitive y string → number permite explicar también casos como `[0] == false`. En código de producto uso `===` y conversiones explícitas para que esa secuencia no quede escondida.":
    "Abstract equality does not compare the array and boolean directly. It first converts `false` to the number `0`. It then applies `ToPrimitive` to the array: `[].toString()` produces `''`. Because it is now comparing a string with a number, it converts `''` to `0`; the final result is `0 == 0`, which is `true`. In contrast, `[] === false` is `false` because the types differ and no coercion occurs. I would not memorize only this result: following boolean → number, object → primitive, and string → number also explains cases such as `[0] == false`. In production code I use `===` and explicit conversions so this sequence is not hidden.",
  '`var` tiene scope de función, así que todas las callbacks cierran sobre un único binding `i`. Cuando ejecuta el timer, el loop ya terminó y ese binding vale `3`: `for (var i = 0; i < 3; i++) setTimeout(() => console.log(i));` imprime `3, 3, 3`. Con `let`, la especificación crea un binding nuevo en cada iteración y el resultado es `0, 1, 2`. Otra solución es una factory o IIFE que reciba `i` y genere un parámetro distinto por vuelta. El punto importante no es el timer: es cuántos bindings existen y cuál captura cada función.':
    '`var` has function scope, so every callback closes over one shared `i` binding. When the timer runs, the loop has finished and that binding is `3`: `for (var i = 0; i < 3; i++) setTimeout(() => console.log(i));` prints `3, 3, 3`. With `let`, the specification creates a new binding for every iteration, producing `0, 1, 2`. Another solution is a factory or IIFE that receives `i` and creates a distinct parameter for each iteration. The important point is not the timer: it is how many bindings exist and which one each function captures.',
  'Mientras una función sea alcanzable, también permanecen alcanzables los valores de su entorno que necesita. Un listener global que captura el componente, un timer que captura una respuesta grande o una cache sin límite pueden mantener vivo ese grafo después de retirar la vista. No todo closure es un leak: se vuelve problema cuando la vida de la referencia supera la vida útil del dato. Remuevo listeners, limpio timers y suscripciones, limito caches y capturo sólo el identificador o valor pequeño necesario. En Angular asocio el cleanup a `DestroyRef` o `takeUntilDestroyed` cuando corresponde.':
    'While a function is reachable, the values it needs from its environment also remain reachable. A global listener that captures a component, a timer that captures a large response, or an unbounded cache can keep that graph alive after the view is removed. Not every closure is a leak: it becomes a problem when the reference outlives the useful lifetime of the data. I remove listeners, clear timers and subscriptions, limit caches, and capture only the necessary identifier or small value. In Angular I connect cleanup to `DestroyRef` or `takeUntilDestroyed` when appropriate.',
  "En una conversión explícita el código declara la intención: `Number(input.value)`, `String(id)` o `Boolean(flag)`. La coerción implícita ocurre dentro de un operador o contexto: `'5' - 1` produce `4`, `1 + '2'` produce `'12'` y `if ('false')` entra porque el string no está vacío. La coerción no es automáticamente un error; templates, comparaciones y operadores dependen de ella. El riesgo aparece cuando oculta un contrato. En fronteras externas convierto, valido y conservo desde allí un tipo estable.":
    "With explicit conversion, the code states its intention: `Number(input.value)`, `String(id)`, or `Boolean(flag)`. Implicit coercion occurs inside an operator or context: `'5' - 1` produces `4`, `1 + '2'` produces `'12'`, and `if ('false')` enters because the string is not empty. Coercion is not automatically an error; templates, comparisons, and operators depend on it. The risk appears when it hides a contract. At external boundaries I convert, validate, and keep a stable type from that point onward.",
  "`ToPrimitive` es la operación abstracta que convierte un objeto en un valor primitivo antes de que otro algoritmo continúe. Si existe, llama a `Symbol.toPrimitive`; en caso contrario prueba `valueOf` y `toString` en un orden que depende del hint. Deben devolver un primitivo o la conversión falla con `TypeError`. Por eso `[] + 1` produce `'1'`: el array se vuelve `''` y `+` concatena. Un objeto puede personalizar el resultado con `[Symbol.toPrimitive](hint)`, pero hacerlo de forma sorprendente vuelve los operadores difíciles de razonar; normalmente prefiero métodos explícitos de dominio.":
    "`ToPrimitive` is the abstract operation that converts an object into a primitive value before another algorithm continues. If present, it calls `Symbol.toPrimitive`; otherwise it tries `valueOf` and `toString` in an order determined by the hint. They must return a primitive or conversion fails with a `TypeError`. That is why `[] + 1` produces `'1'`: the array becomes `''` and `+` concatenates. An object can customize the result with `[Symbol.toPrimitive](hint)`, but surprising behavior makes operators difficult to reason about; I normally prefer explicit domain methods.",
};
