// Generated by tools/generate_site_spanish_translations.mjs.
// The English portfolio copy remains canonical in its components and services.

export const SITE_SPANISH_TRANSLATIONS: Readonly<Record<string, string>> = {
  '30': '30',
  '227': '227',
  '260': '260',
  'Show selected credentials': 'Mostrar credenciales seleccionadas',
  'View all credentials': 'Ver todas las credenciales',
  'View credential': 'Ver credencial',
  Present: 'presente',
  total: 'total',
  'Full-Stack Product Engineer': 'Ingeniero de Producto Full-Stack',
  'Primary navigation': 'Navegación primaria',
  Work: 'trabajo',
  Experience: 'Experiencia',
  Background: 'Antecedentes',
  'Toggle navigation': 'Alternar navegación',
  'Mobile navigation': 'Navegación móvil',
  "Let's talk": 'hablemos',
  AC: 'aire acondicionado',
  'Adrian Cabello': 'Adrián Cabello',
  'Adrian Cabello, Full-Stack Product Engineer and Tech Lead':
    'Adrian Cabello, ingeniero de producto Full-Stack y líder tecnológico',
  'Argentina · Remote': 'Argentina · Remoto',
  'Building products, systems and engineering teams.':
    'Construcción de productos, sistemas y equipos de ingeniería.',
  'Full-Stack Product Engineer · Tech Lead':
    'Ingeniero de Producto Full-Stack · Líder Técnico',
  'I build complex products': 'Construyo productos complejos',
  'from interface to infrastructure.':
    'desde la interfaz hasta la infraestructura.',
  '9+ years of experience': 'Más de 9 años de experiencia',
  'building scalable web and mobile products, leading Angular architecture and migrations, and shipping end-to-end systems with Ionic, Go, Node.js and PostgreSQL.':
    'creando productos web y móviles escalables, liderando la arquitectura y las migraciones de Angular y enviando sistemas de extremo a extremo con Ionic, Go, Node.js y PostgreSQL.',
  'View experience': 'Ver experiencia',
  'Download résumé': 'Descargar currículum',
  'Contact me': 'Contáctame',
  '9+ years': '9+ años',
  Mobile: 'Móvil',
  Backend: 'backend',
  'Visit Adrian Cabello on LinkedIn': 'Visita Adrián Cabello en LinkedIn',
  'Visit Adrian Cabello on GitHub': 'Visita Adrián Cabello en GitHub',
  "I'm Adrian Cabello, a product engineer with":
    'Soy Adrián Cabello, ingeniero de producto con',
  "I've built Ionic ordering and geolocated delivery workflows for Coca-Cola and Unilever programs, migrated a large enterprise application to Angular 19 with Signals, and use LLMs, MCP and automation in day-to-day delivery.":
    'Creé pedidos Ionic y flujos de trabajo de entrega geolocalizados para programas de Coca-Cola y Unilever, migré una aplicación empresarial grande a Angular 19 con Signals y utilicé LLMs, MCP y automatización en las entregas del día a día.',
  Angular: 'Angular',
  '2—22': '2—22',
  Ionic: 'Ionic',
  'Go + Node': 'Go + Nodo',
  LinkedIn: 'LinkedIn',
  GitHub: 'GitHub',
  'Selected work': 'Trabajo seleccionado',
  'Products where I owned more than the interface.':
    'Productos en los que poseía más que la interfaz.',
  'Architecture, delivery, product decisions and the systems behind the screen — not just a list of technologies.':
    'Arquitectura, entrega, decisiones de productos y los sistemas detrás de la pantalla: no solo una lista de tecnologías.',
  'Flagship product': 'Producto estrella',
  'Product view': 'Vista del producto',
  'Technologies used': 'Tecnologías utilizadas',
  'Explore EventLoop': 'Explorar EventLoop',
  'Visit site': 'Visitar sitio',
  Instagram: 'Instagram',
  '} }': '} }',
  'From enterprise platforms to founder-led product ownership.':
    'Desde plataformas empresariales hasta propiedad de productos liderada por los fundadores.',
  'The common thread is ownership: making architecture clearer, delivery safer and complex workflows easier to use.':
    'El hilo conductor es la propiedad: hacer que la arquitectura sea más clara, la entrega más segura y los flujos de trabajo complejos más fáciles de usar.',
  'Key contributions': 'Contribuciones clave',
  Education: 'educación',
  'A technical foundation built through practice.':
    'Una base técnica construida a través de la práctica.',
  'Selected training': 'Formación seleccionada',
  'Recent, relevant credentials.': 'Credenciales recientes y relevantes.',
  'Technical resources': 'Recursos técnicos',
  'Knowledge is more useful when it is shared.':
    'El conocimiento es más útil cuando se comparte.',
  'I turn production experience into practical material that engineers can study, discuss and apply.':
    'Convierto la experiencia de producción en material práctico que los ingenieros pueden estudiar, discutir y aplicar.',
  'Open resource · Spanish': 'Recurso abierto · Español',
  'Angular Senior Interview Guide':
    'Guía de entrevistas para personas mayores Angular',
  'A complete study system covering modern Angular, TypeScript, JavaScript, browser fundamentals, HTML, CSS, RxJS, architecture, performance, testing, security and senior engineering judgment. Every topic combines theory with interview questions, concrete answers and practical cases.':
    'Un sistema de estudio completo que cubre los modernos Angular, TypeScript, JavaScript, fundamentos del navegador, HTML, CSS, RxJS, arquitectura, rendimiento, pruebas, seguridad y criterio de ingeniería senior. Cada tema combina teoría con preguntas de entrevistas, respuestas concretas y casos prácticos.',
  'Built and maintained by Adrian Cabello from more than nine years of product engineering, Angular architecture and technical leadership experience.':
    'Construido y mantenido por Adrian Cabello a partir de más de nueve años de ingeniería de productos, arquitectura Angular y experiencia en liderazgo técnico.',
  Topics: 'Temas',
  Concepts: 'Conceptos',
  Questions: 'Preguntas',
  Format: 'Formato',
  'Theory + Q&A': 'Teoría + Preguntas y respuestas',
  'Explore the guide': 'Explora la guía',
  'Guide coverage': 'Cobertura de la guía',
  'Inside the guide': 'Dentro de la guía',
  'HTML, CSS, JavaScript and TypeScript': 'HTML, CSS, JavaScript y TypeScript',
  'Modern Angular, Signals, RxJS and forms':
    'Angular, Signals, RxJS y formas modernas',
  'Architecture, patterns and system design':
    'Arquitectura, patrones y diseño de sistemas.',
  'Performance, testing, security and delivery':
    'Rendimiento, pruebas, seguridad y entrega',
  'Leadership, trade-offs and interview practice':
    'Liderazgo, compensaciones y práctica de entrevistas.',
  'One continuous study path': 'Un camino de estudio continuo',
  'Searchable, progress-aware and designed to move from fundamentals to senior-level decisions without losing context.':
    'Buscable, consciente del progreso y diseñado para pasar de los fundamentos a las decisiones de nivel superior sin perder el contexto.',
  'Angular 22': 'Angular 22',
  '01': '01',
  '02': '02',
  '03': '03',
  '04': '04',
  '05': '05',
  'Built with Angular and product-minded engineering.':
    'Construido con Angular e ingeniería centrada en el producto.',
  EventLoop: 'EventLoop',
  'Founder & Tech Lead': 'Fundador y líder tecnológico',
  'The operating system behind event discovery, ticketing, producer operations, artist profiles, point of sale, inventory and branded public websites.':
    'El sistema operativo detrás del descubrimiento de eventos, venta de entradas, operaciones de productores, perfiles de artistas, puntos de venta, inventario y sitios web públicos de marca.',
  'Own product strategy, UX, architecture, backend systems and production releases.':
    'Estrategia propia de producto, UX, arquitectura, sistemas backend y lanzamientos de producción.',
  'Built one platform serving attendees, producers, venues and artists.':
    'Construyó una plataforma que atiende a asistentes, productores, lugares y artistas.',
  'Launched productized custom-domain websites powered and managed from EventLoop.':
    'Se lanzaron sitios web de dominio personalizado desarrollados y administrados desde EventLoop.',
  'Event discovery': 'Descubrimiento de eventos',
  'Event page & ticketing': 'Página del evento y venta de entradas',
  Adricted: 'adicto',
  'Artist website · Powered by EventLoop':
    'Sitio web del artista · Desarrollado por EventLoop',
  'A branded artist website generated from EventLoop and published on adricted.com through the platform’s custom-domain offering.':
    'Un sitio web de artista de marca generado a partir de EventLoop y publicado en adricted.com a través de la oferta de dominio personalizado de la plataforma.',
  'Brings events, music, galleries, biography and verified channels into one profile.':
    'Reúne eventos, música, galerías, biografía y canales verificados en un solo perfil.',
  'Uses EventLoop as the content platform while the artist owns the public domain.':
    'Utiliza EventLoop como plataforma de contenido mientras que el artista es propietario del dominio público.',
  'Live artist profile on adricted.com':
    'Perfil de artista en vivo en adicted.com',
  'Custom domain · Content managed inside EventLoop':
    'Dominio personalizado · Contenido gestionado dentro de EventLoop',
  Markama: 'marcama',
  'Producer website · Powered by EventLoop':
    'Sitio web del productor · Desarrollado por EventLoop',
  'A producer website served by EventLoop at markama.ar, turning the organization profile into a branded destination with its own domain.':
    'Un sitio web productor atendido por EventLoop en markama.ar, convirtiendo el perfil de la organización en un destino de marca con dominio propio.',
  'Publishes events, artists, venues, history and contact information from one workspace.':
    'Publica eventos, artistas, lugares, historia e información de contacto desde un espacio de trabajo.',
  'Demonstrates the productized custom-domain offering available to EventLoop producers.':
    'Demuestra la oferta de dominio personalizado productizado disponible para los productores de EventLoop.',
  'Live producer profile on markama.ar':
    'Perfil del productor en vivo en markama.ar',
  'Haircut & Chill': 'Corte de pelo y relajación',
  'Client website': 'Sitio web del cliente',
  'A conversion-focused website for JuanSe Favoretti’s hair studio in Tandil, combining a strong editorial identity with clear services, haircut inspiration and direct booking paths.':
    'Un sitio web centrado en la conversión para el estudio de peluquería de JuanSe Favoretti en Tandil, que combina una fuerte identidad editorial con servicios claros, inspiración en cortes de cabello y rutas de reserva directa.',
  'Designed the experience around the studio’s relaxed, craft-led identity.':
    'Diseñó la experiencia en torno a la identidad relajada y artesanal del estudio.',
  'Connected Calendly, WhatsApp and Instagram so visitors can book through their preferred channel.':
    'Conectado Calendly, WhatsApp y Instagram para que los visitantes puedan reservar a través de su canal preferido.',
  'Built a filterable haircut catalogue that turns visual inspiration into a useful consultation tool.':
    'Creó un catálogo de cortes de cabello filtrable que convierte la inspiración visual en una útil herramienta de consulta.',
  'Haircut & Chill website': 'Sitio web de Haircut & Chill',
  'Leonela Cabello': 'Leonela Cabello',
  'A professional website for an independent lawyer, translating complex legal services into a clear, approachable experience built around trust and easy first contact.':
    'Un sitio web profesional para un abogado independiente, que traduce servicios legales complejos en una experiencia clara y accesible basada en la confianza y un primer contacto sencillo.',
  'Structured six legal service areas so visitors can quickly understand where to start.':
    'Se estructuraron seis áreas de servicios legales para que los visitantes puedan entender rápidamente por dónde empezar.',
  'Created a confident editorial identity that balances professionalism with a personal presence.':
    'Creé una identidad editorial segura que equilibra el profesionalismo con una presencia personal.',
  'Integrated WhatsApp and Calendly as direct conversion paths for prospective clients.':
    'WhatsApp y Calendly integrados como rutas de conversión directa para clientes potenciales.',
  'Leonela Cabello legal website': 'Sitio legal de Leonela Cabello',
  'Lautaro Vulcano': 'Volcán Lautaro',
  'Selected client work': 'Trabajo de cliente seleccionado',
  'A focused portfolio for a visual designer, shaped around clear communication, responsive presentation and an easy path from work samples to contact.':
    'Un portafolio enfocado para un diseñador visual, basado en una comunicación clara, una presentación responsiva y un camino sencillo desde las muestras de trabajo hasta el contacto.',
  'Designed and delivered the responsive Angular experience.':
    'Diseñó y entregó la experiencia responsiva Angular.',
  'Created a visual system tailored to the client’s identity.':
    'Creé un sistema visual adaptado a la identidad del cliente.',
  'Senior Frontend Engineer': 'Ingeniero Frontend Senior',
  'Jun 2025 - Present': 'Junio de 2025 - Presente',
  'Building production Angular features for data-rich and AI-enabled workflows in a cross-functional product environment.':
    'Cree funciones de producción Angular para flujos de trabajo ricos en datos y habilitados para AI en un entorno de producto multifuncional.',
  'Build and maintain production frontend features with Angular and TypeScript.':
    'Cree y mantenga funciones de interfaz de producción con Angular y TypeScript.',
  'Integrate data-rich and AI-enabled workflows while improving maintainability, usability, and frontend architecture.':
    'Integre flujos de trabajo ricos en datos y habilitados para AI mientras mejora la mantenibilidad, la usabilidad y la arquitectura frontend.',
  'Collaborate with product, backend, design, and QA across the full delivery lifecycle.':
    'Colabore con el producto, el backend, el diseño y el control de calidad durante todo el ciclo de vida de entrega.',
  'Dec 2023 - Present': 'Dic. 2023 - Presente',
  'Leading product strategy, UX, architecture and delivery for an event operations platform spanning ticketing, POS, inventory and multi-location workflows.':
    'Estrategia de producto líder, UX, arquitectura y entrega para una plataforma de operaciones de eventos que abarca venta de entradas, POS, inventario y flujos de trabajo en múltiples ubicaciones.',
  'Lead product strategy, UX, frontend architecture, releases, and continuous iteration.':
    'Liderar la estrategia de producto, UX, arquitectura frontend, lanzamientos e iteración continua.',
  'Built Angular 22 and TypeScript workflows for POS, ticketing, inventory, product catalogs, and multi-location operations.':
    'Creó flujos de trabajo Angular 22 y TypeScript para POS, emisión de boletos, inventario, catálogos de productos y operaciones en múltiples ubicaciones.',
  'Implemented role-based access, receipt OCR imports, recipe-linked stock, and real-time inventory synchronization.':
    'Se implementó acceso basado en roles, importaciones de recibos OCR, stock vinculado a recetas y sincronización de inventario en tiempo real.',
  'Contribute to Go backend services and PostgreSQL data models while guiding technical decisions across the product.':
    'Contribuya a los servicios de backend Go y a los modelos de datos PostgreSQL mientras guía las decisiones técnicas en todo el producto.',
  'Senior Frontend Developer': 'Desarrollador front-end sénior',
  'May 2024 - January 2025': 'mayo 2024 - enero 2025',
  'Built an Ionic ordering platform for field sales and distribution teams while contributing to a large enterprise migration to Angular 19 and developing new analytics workflows with Signals.':
    'Creó una plataforma de pedidos Ionic para equipos de ventas y distribución de campo y al mismo tiempo contribuyó a una gran migración empresarial a Angular 19 y desarrolló nuevos flujos de trabajo de análisis con Signals.',
  'Built an Ionic and Angular mobile ordering app for field sales and distribution teams supporting Coca-Cola and Unilever programs.':
    'Creé una aplicación de pedidos móviles Ionic y Angular para los equipos de ventas y distribución de campo que respaldan los programas de Coca-Cola y Unilever.',
  'Delivered visit planning, customer-specific catalogs, order and return capture, offline sync, delivery tracking, and geolocated seller routes.':
    'Planificación de visitas entregadas, catálogos específicos de clientes, captura de pedidos y devoluciones, sincronización fuera de línea, seguimiento de entregas y rutas de vendedores geolocalizadas.',
  'Migrated a large enterprise application to Angular 19 and developed new analytics features with Signals.':
    'Migré una aplicación empresarial grande a Angular 19 y desarrollé nuevas funciones de análisis con Signals.',
  'Used deferred loading, hydration, reusable components, and REST integrations to improve performance and scalability.':
    'Se utilizaron carga diferida, hidratación, componentes reutilizables e integraciones REST para mejorar el rendimiento y la escalabilidad.',
  'Tech stack: Angular 19, Ionic, TypeScript, RxJS, Signals, HTML5, CSS3, SASS.':
    'Pila de tecnología: Angular 19, Ionic, TypeScript, RxJS, Signals, HTML5, CSS3, SASS.',
  'Senior Frontend Developer / Frontend Lead':
    'Desarrollador Frontend Senior / Líder Frontend',
  'Jun 2022 – Apr 2024': 'junio de 2022 – abril de 2024',
  'Worked on multiple AI-powered and investment-oriented web platforms for Mercer, including RFP, Mercer Mind, Catalytic Investment Exchange, and the Mercer homepage. Focused on building scalable, testable, and responsive frontend solutions using Angular and RxJS, including real-time LLM-powered product experiences.':
    'Trabajó en múltiples plataformas web orientadas a la inversión y basadas en AI para Mercer, incluidas RFP, Mercer Mind, Catalytic Investment Exchange y la página de inicio de Mercer. Centrado en crear soluciones frontend escalables, comprobables y responsivas utilizando Angular y RxJS, incluidas experiencias de productos en tiempo real impulsadas por LLM.',
  'Mercer | RFP': 'Mercero | RFP',
  'Developed an AI-powered platform that allows users to upload files with questions and receive AI-generated responses.':
    'Desarrollé una plataforma impulsada por AI que permite a los usuarios cargar archivos con preguntas y recibir respuestas generadas por AI.',
  'Led the front-end team and built the application from scratch.':
    'Lideré el equipo de front-end y creé la aplicación desde cero.',
  'Developed a file upload system and integrated real-time AI responses.':
    'Desarrollé un sistema de carga de archivos e integré respuestas AI en tiempo real.',
  'Designed AI-assisted workflows for document analysis, answer generation, and user review loops.':
    'Diseñé flujos de trabajo asistidos por AI para análisis de documentos, generación de respuestas y bucles de revisión de usuarios.',
  'Ensured 80%+ unit test coverage for stability.':
    'Aseguró una cobertura de prueba unitaria de más del 80 % para mayor estabilidad.',
  'Tech stack: Angular 17, TypeScript, RxJS, HTML5, CSS3, SASS.':
    'Pila de tecnología: Angular 17, TypeScript, RxJS, HTML5, CSS3, SASS.',
  'Mercer | Mercer Mind': 'Mercero | Mente Mercer',
  'Created an AI chatbot that enables customers to interact with a virtual assistant trained on company data.':
    'Creé un chatbot AI que permite a los clientes interactuar con un asistente virtual capacitado en datos de la empresa.',
  'Developed a real-time chat interface with AI-driven responses.':
    'Desarrollé una interfaz de chat en tiempo real con respuestas basadas en AI.',
  'Used RxJS for state management and secured authentication.':
    'Se utilizó RxJS para gestión de estado y autenticación segura.',
  'Worked with AI interaction patterns including prompt flows, contextual responses, and automated knowledge retrieval.':
    'Trabajé con patrones de interacción AI, incluidos flujos rápidos, respuestas contextuales y recuperación automatizada de conocimientos.',
  'Maintained 80%+ unit test coverage for reliability.':
    'Mantuve una cobertura de pruebas unitarias de más del 80 % para mayor confiabilidad.',
  'Tech stack: Angular 16, TypeScript, RxJS, HTML5, CSS3, SASS.':
    'Pila de tecnología: Angular 16, TypeScript, RxJS, HTML5, CSS3, SASS.',
  'Mercer | Catalytic Investment Exchange':
    'Mercero | Intercambio Catalítico de Inversiones',
  'An online platform connecting investors and dealmakers for investment opportunities.':
    'Una plataforma en línea que conecta a inversores y negociadores en busca de oportunidades de inversión.',
  'Designed and built the UI from scratch, optimizing user workflows.':
    'Diseñé y construí el UI desde cero, optimizando los flujos de trabajo de los usuarios.',
  'Implemented real-time messaging, notifications, and secure authentication.':
    'Implementación de mensajería en tiempo real, notificaciones y autenticación segura.',
  '80%+ unit test coverage for code stability.':
    'Más del 80% de cobertura de pruebas unitarias para la estabilidad del código.',
  'Tech stack: Angular 14, TypeScript, RxJS, HTML5, CSS3, SASS.':
    'Pila de tecnología: Angular 14, TypeScript, RxJS, HTML5, CSS3, SASS.',
  'Mercer | Homepage': 'Mercero | Página de inicio',
  "Developed Mercer's homepage and landing page, showcasing its services and mission.":
    'Desarrollé la página de inicio y la página de destino de Mercer, mostrando sus servicios y misión.',
  'Led front-end development, ensuring responsiveness and performance.':
    'Lideré el desarrollo front-end, garantizando capacidad de respuesta y rendimiento.',
  'Built dynamic content sections and improved SEO.':
    'Se crearon secciones de contenido dinámico y se mejoró SEO.',
  '80%+ unit test coverage for maintainability.':
    'Más del 80% de cobertura de pruebas unitarias para mantenibilidad.',
  'Tech stack: Angular 12, TypeScript, HTML5, CSS3, SASS.':
    'Pila de tecnología: Angular 12, TypeScript, HTML5, CSS3, SASS.',
  'Mar 2021 - Jun 2022': 'marzo de 2021 - junio de 2022',
  'Worked on the EY Global Tax Platform (GTP), an end-to-end solution designed to streamline tax operations for multinational organizations. The platform enables real-time access to global tax data, helping clients identify opportunities, meet obligations, and mitigate risks.':
    'Trabajé en EY Global Tax Platform (GTP), una solución de extremo a extremo diseñada para agilizar las operaciones tributarias para organizaciones multinacionales. La plataforma permite el acceso en tiempo real a datos fiscales globales, lo que ayuda a los clientes a identificar oportunidades, cumplir obligaciones y mitigar riesgos.',
  'Developed and implemented new features to enhance platform functionality and user experience.':
    'Desarrollé e implementé nuevas funciones para mejorar la funcionalidad de la plataforma y la experiencia del usuario.',
  'Refactored and optimized existing code, improving performance, scalability, and maintainability.':
    'Código existente refactorizado y optimizado, mejorando el rendimiento, la escalabilidad y la mantenibilidad.',
  'Built dynamic and reusable components to improve code efficiency and facilitate future development.':
    'Construí componentes dinámicos y reutilizables para mejorar la eficiencia del código y facilitar el desarrollo futuro.',
  'Developed and integrated API consumption services, ensuring seamless data communication between the front-end and back-end.':
    'Servicios de consumo de API desarrollados e integrados, asegurando una comunicación de datos fluida entre el front-end y el back-end.',
  'Implemented state management solutions using Redux to handle complex application states effectively.':
    'Implementé soluciones de administración de estado utilizando Redux para manejar estados de aplicaciones complejos de manera efectiva.',
  'Created interactive UI components and modals, improving workflow efficiency.':
    'Creé componentes y modales interactivos UI, mejorando la eficiencia del flujo de trabajo.',
  'Maintained 80%+ unit test coverage for new and refactored functionalities using Jasmine.':
    'Mantuve una cobertura de pruebas unitarias superior al 80 % para funcionalidades nuevas y refactorizadas utilizando Jasmine.',
  'Resolved bugs and performance issues, enhancing overall platform stability.':
    'Se resolvieron errores y problemas de rendimiento, mejorando la estabilidad general de la plataforma.',
  'Tech stack: Angular 11, Redux, HTML5, CSS3, SASS, RESTful services, and Jasmine.':
    'Pila de tecnología: Angular 11, Redux, HTML5, CSS3, SASS, servicios RESTful y Jasmine.',
  'Semi-Sr Frontend Developer': 'Desarrollador Frontend Semi Senior',
  'Jun 2019 - Mar 2021': 'junio de 2019 - marzo de 2021',
  'Symplr is a leading provider of healthcare governance, risk management, and compliance (GRC) solutions, delivering tailored software that enhances operational efficiency and ensures regulatory compliance.':
    'Symplr es un proveedor líder de soluciones de cumplimiento, gestión de riesgos y gobernanza de la atención médica (GRC), que ofrece software personalizado que mejora la eficiencia operativa y garantiza el cumplimiento normativo.',
  'Developed and optimized new features to enhance platform functionality and user experience.':
    'Desarrollé y optimicé nuevas funciones para mejorar la funcionalidad de la plataforma y la experiencia del usuario.',
  'Designed and implemented administrative forms for managing users, supplies, events, and providers.':
    'Diseñé e implementé formularios administrativos para la gestión de usuarios, insumos, eventos y proveedores.',
  'Created summary profile views, improving accessibility and usability.':
    'Creé vistas de perfil resumidas, mejorando la accesibilidad y usabilidad.',
  'Built modals and interactive UI components to streamline workflows and boost efficiency.':
    'Modales creados y componentes UI interactivos para optimizar los flujos de trabajo y aumentar la eficiencia.',
  'Worked extensively with Redux and Store for state management, ensuring optimal data flow and application performance.':
    'Trabajé extensamente con Redux y Store para la gestión del estado, garantizando un flujo de datos y un rendimiento de las aplicaciones óptimos.',
  'Ensured 80%+ unit test coverage on new and refactored code using Jasmine, improving software reliability.':
    'Aseguré una cobertura de pruebas unitarias de más del 80 % en código nuevo y refactorizado utilizando Jasmine, mejorando la confiabilidad del software.',
  'Collaborated within a cross-functional team of over 100 developers, designers, and product managers, following Agile methodologies.':
    'Colaboré dentro de un equipo multifuncional de más de 100 desarrolladores, diseñadores y gerentes de producto, siguiendo metodologías ágiles.',
  'Worked with a modern tech stack: Angular 9, Redux, Store, HTML5, CSS3, SASS, and RESTful APIs.':
    'Trabajó con una pila de tecnología moderna: Angular 9, Redux, Store, HTML5, CSS3, SASS y API RESTful.',
  'Frontend Developer': 'Desarrollador front-end',
  'Dec 2016 - Jun 2019': 'Dic 2016 - Jun 2019',
  'Worked on web platforms for clients in the finance and retail sectors, building scalable and secure systems that streamlined loan processing and customer engagement.':
    'Trabajó en plataformas web para clientes de los sectores financiero y minorista, creando sistemas escalables y seguros que agilizaron el procesamiento de préstamos y la participación del cliente.',
  'Client: Commodity Finance': 'Cliente: Financiación de productos básicos',
  'Built a secure inventory loan processing system that connects lenders and merchants through digital documentation, streamlining the origination, servicing, and distribution of commodity inventory financing.':
    'Creó un sistema seguro de procesamiento de préstamos de inventario que conecta a prestamistas y comerciantes a través de documentación digital, agilizando el origen, el servicio y la distribución del financiamiento de inventario de productos básicos.',
  'Implemented authentication using Redux & LocalStorage.':
    'Autenticación implementada utilizando Redux y LocalStorage.',
  'Developed user registration and account management features.':
    'Funciones desarrolladas de registro de usuarios y gestión de cuentas.',
  'Created dynamic navigation with Angular Router and lazy loading.':
    'Navegación dinámica creada con enrutador Angular y carga diferida.',
  'Designed a responsive UI with Angular Material.':
    'Diseñó un UI responsivo con material Angular.',
  'Developed modals and role-based access control.':
    'Modales desarrollados y control de acceso basado en roles.',
  'Built a user summary and profile editing system.':
    'Construí un sistema de edición de perfiles y resumen de usuarios.',
  'Created an item list with filtering and pagination.':
    'Creé una lista de elementos con filtrado y paginación.',
  'Developed dynamic forms generated from JSON.':
    'Desarrollé formularios dinámicos generados a partir de JSON.',
  'Built negotiation forms (Create, Update, Delete).':
    'Formularios de negociación construidos (Crear, Actualizar, Eliminar).',
  'Implemented a real-time chat system for intercompany communication.':
    'Implementé un sistema de chat en tiempo real para la comunicación entre empresas.',
  'Integrated Google Analytics for usage tracking.':
    'Google Analytics integrado para seguimiento de uso.',
  'Maintained 80%+ unit test coverage on new and refactored code.':
    'Mantuve una cobertura de pruebas unitarias de más del 80% en código nuevo y refactorizado.',
  'Tech stack: Angular 7, Jasmine, HTML5, CSS3, SASS, RESTful services.':
    'Pila de tecnología: Angular 7, Jasmine, HTML5, CSS3, SASS, servicios RESTful.',
  'Client: OCP': 'Cliente: OCP',
  'Developed a platform to better understand customers, measure in-store traffic, manage the sales force, and execute personalized promotions—all in one tool.':
    'Desarrollé una plataforma para comprender mejor a los clientes, medir el tráfico interno-store, administrar la fuerza de ventas y ejecutar promociones personalizadas, todo en una sola herramienta.',
  'Implemented authentication using LocalStorage.':
    'Autenticación implementada mediante LocalStorage.',
  'Developed user registration and authentication features.':
    'Funciones desarrolladas de registro y autenticación de usuarios.',
  'Designed and built a fully responsive UI.':
    'Diseñado y construido un UI totalmente responsivo.',
  'Created and optimized modals for seamless interactions.':
    'Modales creados y optimizados para interacciones fluidas.',
  'Implemented store and region management functionalities.':
    'Implementé store y funcionalidades de gestión de regiones.',
  'Developed an item listing system with filtering and pagination.':
    'Desarrollé un sistema de listado de artículos con filtrado y paginación.',
  'Integrated a role-based access control system.':
    'Integra un sistema de control de acceso basado en roles.',
  'Tech stack: Angular 4, HTML5, CSS3, SASS, RESTful services.':
    'Pila de tecnología: Angular 4, HTML5, CSS3, SASS, servicios RESTful.',
  'University Technician in Computer Applications':
    'Técnico Universitario en Aplicaciones Informáticas',
  'UNICEN - Tandil, Argentina': 'UNICEN - Tandil, Argentina',
  '2015 - 2018': '2015 - 2018',
  'Development focused program with practical applications in computer science.':
    'Programa enfocado al desarrollo con aplicaciones prácticas en informática.',
  'Software Engineering': 'Ingeniería de software',
  '2012 - 2015': '2012 - 2015',
  'Foundational studies in software engineering principles and practices.':
    'Estudios fundamentales en principios y prácticas de ingeniería de software.',
  'Professional & Personal Computer Technician':
    'Técnico en Computación Personal y Profesional',
  'School of Technical Education Nº3 - Necochea, Argentina':
    'Escuela de Educación Técnica Nº3 - Necochea, Argentina',
  'Graduated 2011': 'Graduado 2011',
  'Technical education focused on computer systems and maintenance.':
    'Educación técnica enfocada en sistemas informáticos y mantenimiento.',
  'Angular Pro: Lleva tus bases al siguiente nivel':
    'Angular Pro: Lleva tus bases al siguiente nivel',
  Udemy: 'Udemy',
  'Mar 2025': 'marzo de 2025',
  'Unit Testing in Angular 12': 'Pruebas unitarias en Angular 12',
  Pluralsight: 'Pluralvista',
  'May 2023': 'mayo 2023',
  'Angular (Basic) Certificate': 'Certificado Angular (Básico)',
  HackerRank: 'HackerRank',
  'May 2022': 'mayo 2022',
  'Angular (Intermediate) Certificate': 'Certificado Angular (Intermedio)',
  'Apr 2022': 'abril de 2022',
  'JavaScript (Basic) Certificate': 'Certificado JavaScript (Básico)',
  'JavaScript (Intermediate) Certificate':
    'Certificado JavaScript (Intermedio)',
  'REDUX en Angular con NGRX: Desde las bases hasta la práctica':
    'REDUX en Angular con NGRX: Desde las bases hasta la práctica',
  'Nov 2021': 'noviembre de 2021',
  'Node: De cero a experto': 'Nodo: De cero a experto',
  'Jan 2020': 'enero de 2020',
  'Curso de Angular 6 avanzado: MEAN, JWT, Módulos, Animaciones':
    'Curso de Angular 6 avanzado: MEAN, JWT, Módulos, Animaciones',
  'Jun 2018': 'junio de 2018',
  'Angular Avanzado: Lleva tus bases al siguiente nivel - MEAN':
    'Angular Avanzado: Lleva tus bases al siguiente nivel - MEAN',
  'Apr 2018': 'abril de 2018',
  'Redux in Angular (2 and 4+)': 'Redux en Angular (2 y 4+)',
  'Mar 2018': 'marzo de 2018',
  'Angular: De cero a experto creando aplicaciones (Angular 5+)':
    'Angular: De cero a experto creando aplicaciones (Angular 5+)',
  'Nov 2017': 'noviembre de 2017',
};
