"""Contenido canónico de IA para la guía de entrevistas Angular Senior."""

AI_CHAPTERS = [
    {
        "title": "IA generativa y panorama de modelos",
        "intro": "Una entrevista de AI Engineer empieza por elegir el tipo de modelo correcto, no por memorizar marcas. Tenés que distinguir capacidades, límites y costo operativo entre modelos comerciales y abiertos.",
        "master": [
            "Machine Learning aprende patrones a partir de datos; Deep Learning usa redes neuronales de múltiples capas; IA generativa produce contenido nuevo. Un LLM es un modelo generativo entrenado para predecir tokens y seguir instrucciones, no una base de datos ni una fuente infalible de hechos.",
            "Los Transformers procesan relaciones entre tokens mediante atención. El pretraining aprende patrones generales; instruction tuning y preferencias humanas ajustan el comportamiento; la inferencia aplica esos parámetros a un contexto concreto.",
            "ChatGPT, Claude y Gemini son productos y familias de modelos de OpenAI, Anthropic y Google. También existen modelos de pesos abiertos —por ejemplo Llama, Mistral, Qwen o gpt-oss— que pueden desplegarse con mayor control. Separá siempre producto, API, modelo y proveedor.",
            "Compará modelos por calidad en la tarea real, modalidades, ventana de contexto, output máximo, latencia, precio por tokens, soporte de herramientas, residencia de datos, rate limits, estabilidad y licencia. Un benchmark público orienta; un eval con datos propios decide.",
            "Un modelo frontier maximiza capacidad pero suele costar más y responder más lento. Modelos pequeños sirven para clasificación, extracción, routing o alto volumen. Model routing puede escalar sólo los casos difíciles, pero añade lógica, evaluación y modos de falla.",
            "Modelos de razonamiento asignan más cómputo a problemas complejos. No implican verdad garantizada: todavía requieren contexto correcto, herramientas, verificación y límites. Para tareas simples, más razonamiento puede sumar latencia y costo sin mejorar el resultado.",
            "Multimodal significa aceptar o producir más de una modalidad: texto, imagen, audio o video. No asumas simetría entre input y output ni la misma calidad en todas; verificá capacidades por modelo y diseñá fallbacks.",
            "Temperatura y otros parámetros de sampling cambian diversidad y repetibilidad, no conocimiento. Para extracción o clasificación preferí salidas estructuradas y baja variación; para ideación permití diversidad y luego evaluá.",
            "Fine-tuning modifica el comportamiento aprendido para una tarea repetible; RAG aporta conocimiento externo en tiempo de ejecución; prompting define instrucciones y ejemplos. Primero medí un baseline y elegí la intervención según el error observado.",
            "Una arquitectura portable encapsula el proveedor detrás de una interfaz propia, pero no finge que todos los modelos son idénticos. Conservá capacidades específicas cuando generan valor y cubrí con contract tests el comportamiento común.",
        ],
        "qa": [
            ("¿Cómo elegirías un modelo?", "Defino calidad mínima, latencia, volumen, modalidades, herramientas, privacidad y presupuesto. Armo un dataset representativo, pruebo dos o tres candidatos con la misma rúbrica y elijo el más barato y rápido que cumpla el umbral, con fallback para casos difíciles."),
            ("¿Modelo open-weight o API administrada?", "Una API acelera entrega y operación; un modelo open-weight aporta control, despliegue privado y posibilidad de ajuste, pero transfiere infraestructura, seguridad y optimización al equipo. La decisión depende de datos, escala, talento operativo y costo total, no sólo del precio por token."),
            ("¿Qué es una alucinación?", "Es una salida plausible pero no respaldada por evidencia o instrucciones. La reduzco con contexto recuperado, herramientas, citas verificables, schemas, abstención y evals; no prometo eliminarla sólo con un prompt."),
            ("¿RAG o fine-tuning?", "Uso RAG cuando cambia el conocimiento, necesito citar o aplicar permisos por documento. Fine-tuning sirve para formato, estilo o patrones estables. Pueden combinarse: el ajuste enseña comportamiento y RAG entrega evidencia fresca."),
            ("¿Cómo evitás lock-in?", "Aíslo el SDK, versiono prompts y schemas, mantengo evals portables y registro capacidades requeridas. No reduzco todo al mínimo común denominador: documento qué features específicas justifican una dependencia."),
        ],
    },
    {
        "title": "Tokens, contexto, prompting y salidas estructuradas",
        "intro": "El prompt es parte de un sistema: instrucciones, datos, historial, herramientas y contrato de salida compiten por una ventana finita. Una respuesta Senior puede explicar qué entra al contexto y cómo se controla.",
        "master": [
            "Un token es una unidad de texto procesada por el modelo; no equivale siempre a una palabra. Input, output, instrucciones, historial y definiciones de herramientas consumen contexto y costo. Medí con el tokenizer y precios del modelo elegido.",
            "La context window limita tokens visibles en una llamada. Una ventana grande no garantiza atención perfecta: priorizá información relevante, orden claro, delimitadores y recuperación selectiva antes de enviar documentos completos.",
            "El system/developer prompt fija políticas y comportamiento; el user prompt expresa la tarea; los resultados de herramientas aportan observaciones. La jerarquía exacta depende de la API, pero los datos recuperados nunca deberían convertirse accidentalmente en instrucciones confiables.",
            "Un prompt robusto declara objetivo, contexto, restricciones, definición de éxito, formato y qué hacer ante incertidumbre. Los ejemplos few-shot enseñan patrones mejor que adjetivos vagos, siempre que representen casos reales y bordes.",
            "Prompt chaining divide un problema en etapas observables: clasificar, recuperar, redactar y verificar. Aumenta control y depuración, pero también latencia, costo y puntos de falla; no lo uses si una única llamada evaluada resuelve bien.",
            "Structured Outputs o JSON Schema convierten la salida en un contrato parseable. Validá igualmente semántica, rangos y permisos en backend: un JSON válido puede contener una decisión incorrecta o peligrosa.",
            "Streaming mejora tiempo percibido al mostrar tokens o eventos progresivamente. La UI necesita cancelar, reconciliar el resultado final, anunciar actualizaciones accesiblemente y distinguir contenido parcial de una respuesta confirmada.",
            "Prompt caching y prefijos reutilizables reducen costo o latencia cuando el proveedor los soporta. Para aprovecharlos, estabilizá el contenido común y colocá lo variable después sin duplicar contexto innecesario.",
            "La memoria de conversación no aparece mágicamente: la aplicación reenvía historial, un resumen o recuerdos recuperados. Definí qué se guarda, durante cuánto tiempo, cómo se edita y cómo se elimina; no mezcles memoria de usuario con conocimiento global.",
            "Versioná prompts, modelo, parámetros, schemas y datasets como código. Un cambio pequeño puede alterar comportamiento; desplegalo con evals offline, canary, métricas y rollback.",
        ],
        "qa": [
            ("¿Qué hace bueno a un prompt de producción?", "Tiene objetivo y límites claros, separa instrucciones de datos, incluye ejemplos representativos, exige un contrato verificable y define abstención. Además está versionado y medido contra un dataset; no depende de frases mágicas."),
            ("¿Cómo manejás una conversación larga?", "Conservo los turnos necesarios, resumo hechos estables, recupero memoria relevante y descarto ruido. Mido pérdida de información con tests y dejo al usuario inspeccionar o corregir la memoria importante."),
            ("¿Por qué JSON Schema no resuelve todo?", "Resuelve forma, no verdad. Después de parsear valido reglas de negocio, referencias, autorización y efectos. Para acciones sensibles uso confirmación y código determinista."),
            ("¿Qué harías si el prompt supera el contexto?", "No lo trunco a ciegas. Priorizo instrucciones, recupero fragmentos relevantes, resumo con trazabilidad, separo la tarea y reservo tokens para la respuesta."),
            ("¿Cómo protegés un prompt del contenido del usuario?", "Delimito datos no confiables, indico que no contienen instrucciones, valido output y limito herramientas en código. El prompt ayuda, pero la frontera real es autorización y control de capacidades fuera del modelo."),
        ],
        "code": """interface CandidateSummary {\n  strengths: string[];\n  risks: string[];\n  evidenceIds: string[];\n  needsHumanReview: boolean;\n}\n\n// El backend pide una salida con schema, la valida y recién después\n// la transforma en estado visible. Nunca ejecuta texto libre como acción.\nconst result = candidateSummarySchema.parse(modelOutput);""",
    },
    {
        "title": "Embeddings, búsqueda semántica y RAG",
        "intro": "RAG es uno de los temas más frecuentes porque conecta IA con backend, datos y producto. La respuesta fuerte explica la cadena completa, sus métricas y por qué recuperar texto no garantiza contestar bien.",
        "master": [
            "Un embedding representa contenido como un vector donde cercanía intenta capturar similitud semántica. Sirve para búsqueda, clustering, recomendación y clasificación; no es reversible como texto ni reemplaza una política de acceso.",
            "Una pipeline RAG ingiere fuentes, extrae texto, divide en chunks, agrega metadata, calcula embeddings e indexa. En consulta, transforma la pregunta, recupera candidatos, opcionalmente rerankea y genera una respuesta con evidencia.",
            "Chunking decide qué unidad puede recuperarse. Chunks demasiado pequeños pierden contexto; demasiado grandes diluyen señal y gastan tokens. Usá estructura del documento, solapamiento medido y metadata como título, versión, tenant, fecha y permisos.",
            "Vector search encuentra similitud semántica; keyword/BM25 conserva coincidencias exactas. La búsqueda híbrida suele funcionar mejor para nombres, códigos y lenguaje natural. Filtros por metadata deben ejecutarse sin filtrar información no autorizada.",
            "Reranking reordena un conjunto pequeño con un modelo más preciso. Query rewriting, multi-query y HyDE pueden mejorar recall, pero agregan costo y riesgo; medí cada etapa en vez de encadenar técnicas por moda.",
            "La respuesta debería citar IDs o fragmentos recuperados y abstenerse cuando la evidencia no alcanza. Las citas se validan contra el texto fuente; pedirlas en el prompt no impide que el modelo invente una referencia.",
            "Evaluá retrieval separado de generation. Para retrieval medí recall@k, precision@k, MRR o nDCG; para la respuesta medí fidelidad a fuentes, completitud, relevancia y exactitud de citas con revisión humana en una muestra.",
            "La actualización exige versionar documentos, reindexar cambios, eliminar contenido revocado e invalidar caches. Guardá lineage desde chunk hasta fuente para auditoría y derecho de borrado.",
            "RAG no es necesario si la respuesta ya está en el contexto corto, una consulta SQL determinista resuelve mejor o una herramienta puede obtener el dato exacto. Elegí el mecanismo más verificable.",
            "La defensa contra indirect prompt injection trata todo documento recuperado como datos no confiables. No permitas que una página instruya al agente para exfiltrar secretos o cambiar permisos; aislá contenido y restringí tools por política.",
        ],
        "qa": [
            ("Diseñá un RAG para documentación interna", "Ingesto fuentes con IDs, versión y ACL; chunking estructural; embeddings e índice híbrido; filtro permisos antes de exponer resultados; rerank de candidatos; respuesta con citas y abstención. Registro retrieval y feedback, evalúo recall y fidelidad, y proceso actualizaciones y borrados."),
            ("¿Cómo elegís tamaño de chunk y top-k?", "Creo preguntas reales con pasajes relevantes etiquetados y hago un barrido. Elijo la combinación que alcanza recall con el menor ruido y costo; no existe un valor universal."),
            ("¿Por qué una buena búsqueda puede terminar en mala respuesta?", "El generador puede ignorar evidencia, mezclar fuentes, inferir de más o recibir contexto contradictorio. Evalúo retrieval y generation por separado y exijo citas verificadas."),
            ("¿Cuándo usarías búsqueda híbrida?", "Cuando conviven significado semántico y términos exactos como SKUs, nombres o errores. Combino scores o rankings y ajusto pesos con el dataset de consultas reales."),
            ("¿Cómo implementás multi-tenant RAG?", "El tenant y ACL forman parte del índice o del filtro obligatorio aplicado antes de retornar chunks. No confío en que el modelo ignore documentos ajenos y pruebo aislamiento con casos adversariales."),
        ],
    },
    {
        "title": "Tool calling, agentes y memoria",
        "intro": "Un agente no es sólo un chatbot con muchas APIs. Es un loop que decide, actúa y observa dentro de límites explícitos. En entrevistas importa tanto la autonomía como la capacidad de detenerla.",
        "master": [
            "Function o tool calling permite que el modelo solicite una función con argumentos estructurados; la aplicación valida, autoriza, ejecuta y devuelve el resultado. El modelo propone la llamada: no obtiene privilegios por sí mismo.",
            "Un workflow fija pasos en código y usa el modelo dentro de algunos; un agente elige dinámicamente próximos pasos. Empezá con workflow cuando el proceso es conocido: ofrece menor variabilidad, latencia y superficie de riesgo.",
            "El loop agentic contiene objetivo, estado, modelo, tools, observaciones y condición de salida. Definí límites de pasos, tiempo, tokens, dinero y reintentos para evitar loops o runaway costs.",
            "Cada tool necesita nombre y descripción inequívocos, schema estrecho, errores útiles e idempotency key para mutaciones reintentables. Separá leer de escribir y preferí operaciones pequeñas, composables y auditables.",
            "Least privilege significa entregar sólo las tools y credenciales necesarias para esa tarea, usuario y turno. La autorización se aplica en el servidor usando identidad real, nunca a partir de un argumento inventado por el modelo.",
            "Para efectos de alto impacto —enviar, comprar, borrar, publicar o desplegar— mostrá un preview y pedí aprobación humana justo antes de ejecutar. La confirmación debe incluir destino y cambios concretos.",
            "La memoria de trabajo vive en el estado del run; la memoria episódica guarda interacciones; la semántica guarda hechos; la procedimental describe cómo actuar. Cada tipo necesita procedencia, caducidad, permisos y corrección.",
            "Plan-and-execute separa planificación de acción; reflection o critic agrega revisión; multi-agent divide roles. Estas técnicas pueden mejorar tareas largas, pero también multiplican tokens, coordinación y errores correlacionados. Se justifican con evals.",
            "Un agente confiable puede reanudar: persiste checkpoints, tool calls, resultados, aprobaciones y versión del workflow. Las acciones externas usan idempotencia y reconciliación para no duplicarse después de un fallo.",
            "La UI debe hacer visible qué está pensando hacer a nivel de plan útil, qué tool ejecuta, qué cambió, qué necesita aprobación y cómo cancelar. No expongas razonamiento privado; sí evidencia, estado y acciones observables.",
        ],
        "qa": [
            ("¿Cuándo usarías un agente?", "Cuando los pasos dependen de observaciones intermedias y no puedo enumerarlos razonablemente. Si el flujo es conocido, prefiero un workflow determinista con llamadas al modelo acotadas."),
            ("¿Quién ejecuta una tool call?", "La aplicación. El modelo devuelve nombre y argumentos; el runtime valida schema, autorización e invariantes, ejecuta la función y entrega la observación al modelo."),
            ("¿Cómo evitás que un agente haga daño?", "Capacidades mínimas, credenciales por usuario, allowlists, sandbox, límites, validación, aprobación para side effects, idempotencia, logs y kill switch. Nunca delego autorización al lenguaje natural."),
            ("¿Qué es memoria en un agente?", "Es estado seleccionado que la aplicación conserva o recupera. Distingo contexto del run, hechos duraderos y procedimientos; cada recuerdo tiene fuente, scope, TTL y opción de corrección."),
            ("¿Multi-agent siempre mejora?", "No. Puede aportar especialización o paralelismo, pero suma costo y coordinación y los agentes pueden repetir el mismo error. Lo adopto sólo si supera un baseline simple en evals y operación."),
        ],
    },
    {
        "title": "Skills, automatizaciones, plugins y MCP",
        "intro": "Estas capas suelen confundirse. Una entrevista moderna espera que puedas explicar qué empaqueta comportamiento, qué conecta capacidades, qué agenda trabajo y dónde viven los permisos.",
        "master": [
            "Una skill es un paquete reusable de instrucciones, reglas, ejemplos, recursos y scripts para realizar un tipo de tarea de forma consistente. Extiende el procedimiento del agente; no concede acceso automáticamente a sistemas externos.",
            "Una tool es una capacidad invocable con un contrato; una skill enseña cuándo y cómo usar capacidades; un plugin empaqueta skills, servidores MCP, apps o configuración para instalar una integración coherente. Los nombres exactos varían por plataforma, por eso explicá responsabilidades antes que branding.",
            "Una automatización agenda o dispara una tarea por tiempo o evento. Necesita identidad de ejecución, zona horaria, reintentos, deduplicación, estado, notificaciones, auditoría y una política clara para acciones que todavía requieren aprobación.",
            "MCP —Model Context Protocol— estandariza cómo un host de IA se conecta con servidores que exponen tools, resources y prompts. El host coordina permisos y contexto; cada cliente mantiene una conexión aislada con un servidor.",
            "En MCP, resources exponen contexto legible, tools ejecutan acciones y prompts ofrecen plantillas reutilizables. El handshake negocia versión y capabilities; no asumas que todos los servidores implementan las mismas primitivas.",
            "Un servidor MCP puede ser local o remoto. Transporte, autenticación y deployment son decisiones separadas del protocolo. Para remoto necesitás OAuth o credenciales equivalentes, scopes mínimos, rotación y protección contra confused deputy.",
            "La seguridad de MCP depende del host y del servidor: consentimiento visible, validación de inputs, control de egress, separación entre servidores y no reenviar toda la conversación si una llamada sólo necesita dos campos.",
            "Diseñá un plugin con manifest versionado, dependencias explícitas, permisos comprensibles, actualización reversible y documentación de datos. Evitá que instalar una integración habilite acciones destructivas por defecto.",
            "Para una skill de calidad definí triggers específicos, procedimiento corto, criterios de salida, scripts repetibles y fallbacks. Evals deben comprobar tanto que se active cuando corresponde como que no se active fuera de scope.",
            "Observá la integración completa: versión de skill/plugin/server, latencia por tool, errores, aprobaciones, tokens agregados al contexto y acciones finales. Un catálogo enorme puede empeorar tool selection; ofrecé sólo capacidades relevantes por turno.",
        ],
        "qa": [
            ("¿Skill, tool, plugin o MCP?", "Skill es conocimiento procedimental reusable; tool es una función ejecutable; plugin es una unidad instalable que agrupa capacidades; MCP es un protocolo cliente-servidor para exponer contexto y acciones. Una automatización define cuándo correr el flujo."),
            ("¿Qué expone un servidor MCP?", "Puede exponer resources, tools y prompts según las capabilities negociadas. El host conserva control de permisos, crea un cliente aislado por servidor y decide qué contexto compartir."),
            ("¿Cómo diseñarías una automatización segura?", "Defino trigger, identidad, zona horaria, inputs versionados, idempotencia, reintentos, límites y auditoría. Las acciones sensibles requieren aprobación o una autorización previa explícita y acotada."),
            ("¿Cómo evaluás una skill?", "Creo casos positivos, negativos y ambiguos; mido activación, cumplimiento del procedimiento, uso correcto de tools, resultado y costo. Versiono skill y dataset para detectar regresiones."),
            ("¿Qué riesgo trae ofrecer cien tools?", "Aumenta tokens, confusión de selección y superficie de ataque. Cargo o permito el subconjunto relevante, uso nombres diferenciados y evalúo llamadas incorrectas."),
        ],
    },
    {
        "title": "Arquitectura de productos con IA y Angular",
        "intro": "El frontend no debe contener claves ni convertirse en un simple textarea. Un producto de IA serio diseña streaming, estados parciales, cancelación, evidencia, feedback y una frontera backend defendible.",
        "master": [
            "Angular llama a un backend propio o AI gateway; nunca expone la API key del proveedor en el bundle. El backend autentica, autoriza, aplica cuotas, arma contexto, invoca modelos y registra telemetría sanitizada.",
            "El gateway desacopla proveedores, centraliza retry, timeout, routing, caching, budgets, moderación y tracing. Mantené los schemas del dominio fuera de detalles del SDK y propagá un correlation ID de UI a tool calls.",
            "Modelá estados explícitos: idle, preparing, streaming, awaiting-approval, completed, cancelled y failed. Un discriminated union evita combinaciones imposibles como mostrar éxito mientras la respuesta sigue abierta.",
            "Para streaming usá SSE, fetch streams o WebSocket según bidireccionalidad. Acumulá eventos con una frecuencia de render razonable, cancelá con AbortController y tratá cierre de red, reconexión y respuesta incompleta.",
            "No renderices Markdown del modelo como HTML confiable. Sanitizá, restringí links e imágenes, aplicá CSP y separá citas o tool results con componentes propios. Nunca ejecutes código producido sin sandbox.",
            "Una chat UI accesible conserva foco, anuncia actualizaciones sin leer cada token, permite pausar movimiento, ofrece copiar y muestra estados. El streaming visual no debe impedir navegación por teclado ni revisión de evidencia.",
            "Optimistic UI sólo corresponde a acciones reversibles y conocidas. Para una tool mutante mostrale al usuario un preview, el scope y el botón de confirmación; después reconciliá el resultado real y explicá fallos parciales.",
            "Rate limits se manejan con backoff y jitter, colas, concurrencia por usuario y mensajes útiles. Retry sólo en errores transitorios y llamadas idempotentes; no repitas ciegamente una compra o envío.",
            "Costos: tokens de entrada/salida, herramientas, embeddings, almacenamiento y observabilidad. Definí presupuesto por request/usuario, max output, compresión de historial, caching y alertas de consumo anormal.",
            "La degradación elegante ofrece reintentar, cambiar a un modelo alternativo o continuar sin IA cuando el feature lo permite. El producto debe seguir explicando qué ocurrió y preservar el trabajo del usuario.",
        ],
        "qa": [
            ("Diseñá un chat con IA en Angular", "Uso backend gateway autenticado; endpoint streaming cancelable; estado con union y Signals; render seguro de Markdown y citas; historial con política de privacidad; feedback; rate limits, tracing y evals. La UI distingue contenido parcial, tool calls, aprobaciones y resultado final."),
            ("¿Por qué no llamar al proveedor desde Angular?", "Expondría credenciales y eludiría autorización, cuotas, auditoría y políticas. El backend es la frontera confiable y puede cambiar proveedor sin desplegar secretos al cliente."),
            ("¿SSE o WebSocket?", "SSE o fetch streaming alcanza para servidor→cliente y simplifica reconexión; WebSocket encaja si necesito mensajes bidireccionales frecuentes. Comparo proxies, auth, escalado y semántica de reanudación."),
            ("¿Cómo limitás costo?", "Presupuestos por solicitud y usuario, modelos escalonados, contexto relevante, max output, caching, batching donde aplique y alertas. Mido costo por resultado exitoso, no sólo tokens promedio."),
            ("¿Cómo probarías la UI streaming?", "Con una fuente determinista de eventos pruebo chunks, cancelación, error medio, reconexión, respuesta vacía, foco y anuncios accesibles. E2E verifica integración sin depender siempre del modelo real."),
        ],
        "code": """type AiRunState =\n  | { kind: 'idle' }\n  | { kind: 'streaming'; text: string; runId: string }\n  | { kind: 'awaiting-approval'; action: ToolPreview }\n  | { kind: 'completed'; answer: Answer; traceId: string }\n  | { kind: 'failed'; recoverable: boolean; message: string };\n\nreadonly runState = signal<AiRunState>({ kind: 'idle' });""",
    },
    {
        "title": "Evals, observabilidad, costo y operación",
        "intro": "Un AI Developer Senior no dice que el resultado ‘parece bueno’. Define datasets, graders, métricas técnicas y de producto, y una forma segura de detectar regresiones antes y después del deploy.",
        "master": [
            "Un eval comienza con tarea, dataset representativo, output esperado o rúbrica y criterio de aceptación. Incluí casos normales, bordes, idiomas, ataques y ejemplos donde el sistema debe abstenerse.",
            "Evals deterministas verifican JSON, regex, compilación, tests o reglas exactas. Human review capta utilidad y matices. LLM-as-judge escala comparación con una rúbrica, pero tiene sesgos y debe calibrarse contra humanos.",
            "Medí componentes: retrieval, selección de tools, argumentos, respuesta y outcome. Una métrica end-to-end sola puede ocultar si falla la búsqueda o el modelo ignora evidencia.",
            "Para comparar prompts o modelos usá el mismo dataset, condiciones y grader; reportá distribución e intervalos, no sólo promedio. Revisá ejemplos donde gana y pierde cada variante antes de decidir.",
            "La evaluación online usa canary o A/B con guardrails. Métricas de producto incluyen resolución, aceptación, edición, tiempo ahorrado y retención; guardrails incluyen quejas, escalaciones, seguridad, latencia y costo.",
            "Tracing registra cada run, versión del prompt/modelo, tiempos, tokens, retrieval, tool calls, errores y outcome. Redactá PII y secretos, aplicá retención y control de acceso; observabilidad no autoriza guardar conversaciones indefinidamente.",
            "Latencia se descompone en queue, time to first token, generación, tools y postprocesamiento. Mejorá la etapa dominante con streaming, paralelismo seguro, caching o modelo menor y verificá que no caiga calidad.",
            "Controlá costo por tarea exitosa y percentiles por segmento. Un modelo barato que requiere tres retries o mucha revisión humana puede costar más que uno fuerte en una sola llamada.",
            "Los fallos de proveedor necesitan timeout, circuit breaker, fallback compatible y runbooks. El fallback se evalúa con los mismos contratos; cambiar silenciosamente de modelo puede alterar seguridad o calidad.",
            "El feedback thumbs up/down sirve sólo si se acompaña de contexto opcional y muestreo. La ausencia de queja no demuestra calidad; convertí fallos revisados en nuevos casos del dataset.",
        ],
        "qa": [
            ("¿Cómo evaluás un feature de IA?", "Construyo dataset desde tráfico y riesgos, baseline, graders deterministas y humanos, y métricas por componente. Defino umbral y guardrails, corro regresión en cada cambio y después hago canary con outcome, latencia, costo y seguridad."),
            ("¿LLM-as-judge es confiable?", "Es útil para escalar una rúbrica, no es verdad absoluta. Fijo versión y prompt, oculto el orden cuando comparo, calibro contra humanos y audito desacuerdos y sesgos."),
            ("¿Qué trazás en un agente?", "Run y parent spans, versiones, decisiones de tool visibles, argumentos redactados, resultados, latencia, tokens, aprobaciones, errores y resultado. Mantengo acceso y retención acordes a la sensibilidad."),
            ("¿Offline eval o A/B test?", "Offline es rápido, reproducible y seguro para regresiones; A/B mide impacto real pero expone usuarios y necesita guardrails. Primero offline, luego canary o experimento cuando el riesgo lo permite."),
            ("¿Cuál es la métrica de costo correcta?", "Costo por outcome útil, segmentado y con p95, incluyendo retries, tools, storage y revisión humana. Tokens por request aislados pueden incentivar respuestas baratas que no resuelven."),
        ],
    },
    {
        "title": "Seguridad, privacidad y uso responsable de IA",
        "intro": "Los sistemas con IA combinan riesgos web clásicos con entradas no confiables, acciones autónomas y resultados probabilísticos. La mitigación real vive en arquitectura, permisos y verificación, no en pedirle al modelo que sea cuidadoso.",
        "master": [
            "Prompt injection intenta convertir contenido no confiable en instrucciones. Puede venir del usuario o de documentos, emails y páginas recuperadas. Delimitá datos, pero aplicá la defensa decisiva fuera del modelo: privilegios mínimos, allowlists y aprobación.",
            "Data exfiltration ocurre si el sistema mezcla secretos o datos de otros usuarios con canales de salida. Segmentá tenants, filtrá retrieval, evitá secretos en prompts y controlá egress de tools y links.",
            "Nunca uses la respuesta del modelo como autorización. La identidad, el rol, ownership del recurso y límites de negocio se validan con código en cada tool, igual que en cualquier API.",
            "PII y datos sensibles requieren minimización, finalidad, consentimiento o base legal, cifrado, retención, borrado y acuerdos con proveedores. Redactá antes de logging y conocé si los datos se usan para entrenamiento.",
            "Output validation cubre schema, negocio, citas, contenido y encoding. Sanitizá HTML/Markdown, parametrizá SQL, escapá comandos y ejecutá código sólo en sandbox sin credenciales ni red salvo necesidad explícita.",
            "Model supply chain incluye proveedor, versión, modelos open-weight, datasets, adapters y dependencias. Fijá versiones cuando sea posible, verificá artefactos, escaneá dependencias y mantené rollback.",
            "Abuso y safety requieren threat modeling por feature: fraude, acoso, malware, autolesión, discriminación o desinformación según dominio. Combiná políticas, clasificadores, límites, revisión humana y respuesta a incidentes.",
            "Sesgo se evalúa con segmentos relevantes y revisión del impacto, no sólo con una frase neutral. Para decisiones de alto impacto, reducì automatización, explicá factores verificables y habilitá apelación humana.",
            "Human-in-the-loop tiene que ser real: contexto suficiente, tiempo, autoridad para rechazar y registro de la decisión. Una confirmación automática o fatigante no reduce riesgo.",
            "Red teaming explora ataques y usos inesperados; los hallazgos se convierten en tests, controles y runbooks. Publicá limitaciones claras y diseñá kill switch para desactivar tools o el feature sin redeploy completo.",
        ],
        "qa": [
            ("¿Cómo mitigás prompt injection?", "Trato usuario y retrieval como datos no confiables, reduzco tools disponibles, valido autorización en cada llamada, controlo destinos, separo lectura de escritura y pido confirmación para impacto alto. Agrego casos adversariales al eval y monitoreo intentos."),
            ("¿El system prompt protege secretos?", "No. Puede reducir algunos ataques, pero no es una frontera de seguridad. Los secretos no entran al contexto salvo necesidad estricta y las tools aplican permisos y egress en código."),
            ("¿Qué datos enviarías al proveedor?", "Sólo los necesarios para una finalidad documentada, tras clasificar sensibilidad y revisar retención, región y entrenamiento. Seudonimizo o redacto cuando puedo y ofrezco borrado según política."),
            ("¿Cómo ejecutás código generado?", "En un sandbox efímero, sin secretos, con filesystem y red restringidos, límites de CPU/memoria/tiempo, dependencias controladas y resultado tratado como no confiable."),
            ("¿Cuándo exigís aprobación humana?", "Antes de acciones irreversibles, externas, financieras, públicas o de alto impacto. La UI muestra exactamente acción, destino y diferencias; la aprobación expira si cambia el plan."),
        ],
    },
    {
        "title": "Entrevista y system design para AI Engineer",
        "intro": "La entrevista combina fundamentos, producto y criterio operativo. Tu objetivo es transformar una demo probabilística en un sistema medible, seguro y mantenible, explicando supuestos y trade-offs.",
        "master": [
            "Aclarà usuario, problema, frecuencia, fuentes, sensibilidad, latencia, calidad mínima, presupuesto y consecuencias del error antes de dibujar componentes. Preguntá qué parte realmente necesita IA.",
            "Proponé un baseline simple: búsqueda, reglas o una llamada con prompt y schema. Después agregá RAG, tools o agentes sólo donde el error observado lo justifique.",
            "Dibujá fronteras: Angular, API/gateway, orquestador, proveedor de modelos, fuentes, índice, tools, cola, storage y observabilidad. Marcá trust boundaries, identidad y flujo de datos.",
            "Estimá volumen: usuarios, requests por segundo, tokens de entrada/salida, concurrencia, tamaño de documentos, tasa de indexado y costo mensual. Declarar supuestos vale más que una cifra inventada.",
            "Diseñá happy path y fallos: timeout del modelo, rate limit, tool caída, chunk sin permiso, JSON inválido, desconexión en streaming, cancelación, duplicado y respuesta insegura.",
            "Elegí métricas antes del deploy: baseline, dataset, success rate, fidelidad, tool accuracy, p95, costo por outcome y guardrails. Explicá cómo recolectar ejemplos nuevos sin violar privacidad.",
            "Incluí rollout: feature flag, entorno sombra si aplica, canary, revisión humana, límites iniciales y rollback. Una demo no necesita la misma autonomía que producción.",
            "En live coding priorizá contrato, estados y tests. Podrían pedir streaming, chat, tool call, RAG básico, clasificación estructurada o un eval runner; verbalizá seguridad y producción aunque el ejercicio sea corto.",
            "Prepará historias reales de uso de copilots y agentes: qué delegaste, cómo verificaste, qué dato no compartiste y qué métrica mejoró. ‘Uso ChatGPT todos los días’ no demuestra criterio de ingeniería.",
            "Preguntá al entrevistador por datasets de evaluación, ownership de prompts, revisión de seguridad, observabilidad, estrategia multi-modelo, datos permitidos y definición de éxito del producto.",
        ],
        "qa": [
            ("Diseñá un asistente para soporte interno", "Aclaro fuentes, permisos y riesgo; empiezo con RAG con citas y abstención; gateway con auth, filtros ACL, streaming y feedback; evalúo retrieval y resolución; agrego tool de crear ticket sólo con preview y aprobación; despliego canary con tracing redactado."),
            ("¿Qué construirías en una prueba de 90 minutos?", "Un vertical slice: contrato tipado, una llamada backend mockeable o real, streaming o structured output, estados de UI, cancelación, un test feliz y uno de error. Explico qué falta para seguridad, evals y operación."),
            ("¿Cómo respondés ‘qué IA usaste’?", "Nombro problema y arquitectura, por qué elegí ese modelo o herramienta, datos y límites, cómo verifiqué outputs y resultado medido. Distingo uso personal de una integración de producción."),
            ("¿Qué preguntas harías sobre un rol AI Developer?", "Qué outcomes esperan, cuánto es prototipo versus producción, qué datos y tools existen, cómo hacen evals y safety, quién opera incidentes y cuánto control hay sobre modelo, prompts e infraestructura."),
            ("¿Qué diferencia a un Senior en IA?", "No el número de frameworks. Puede reducir el problema, medir calidad, diseñar fallos y permisos, controlar costo, comunicar incertidumbre y decidir cuándo no usar un agente o incluso no usar IA."),
        ],
    },
]
